### PR TITLE
Remove /debian as per Marco d'Itri's comment 

### PR DESCRIPTION
**Pull request by szepeviktor**
props. @rfc1036
from https://packages.debian.org/stretch/rbldnsd

### CODE REVIEW

**Comment by rfc1036** [comment]
**PLEASE PLEASE PLEASE DO NOT MERGE THIS!**

If I wanted the debianization to be included in the upstream package then I would have submitted a patch myself. If you do this then I will have to repack the upstream source every time to remove the debian/ directory. Official Debian packages just work this way.

**Comment by szepeviktor** [comment]
@rfc1036 So I should propose to remove /debian?

**Comment by rfc1036** [comment]
Yes.

**Comment by szepeviktor** [comment]
Done.

@rfc1036 Could you link the Debian source?
It is missing from Alioth https://anonscm.debian.org/cgit/users/md/rbldnsd.git

**Comment by rfc1036** [comment]
Nowadays the Debian source repository is https://salsa.debian.org/md/rbldnsd/.

But again, please do not merge it in this upstream repository because it would only make my life harder. If changes are needed in the Debian package then I will be happy to consider them.

**Comment by ammammita** [comment]
Dropping the pull request.

**Pull request closed without merging**
